service: aws-nodejs

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs6.10

functions:
  index:
    handler: dist/getFamily.handler
    events:
      - http:
          path: family
          method: get
  index2:
    handler: dist/getJob.handler
    events:
      - http:
          path: job
          method: get
package:
  include:
    - dist/getFamily.js
    - dist/index2.js
